# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf2e49450f3da579a034640103aeaecf6a41b4e0d653eafce590aa7540b0c75662386041a8209f03d54e6cb1d1ef7da80cccc33c66a63bab33aa6b292d6b32d1

test:
  secret_key_base: 2641c34728ae6830410e1171074ed2c740273e43591fd8a9b5a7491cb8036ff28a2471a11d113b9461a235fafb1c7782c3c0cb7ff963c3af9e0d3a7a55e7c359

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
